services:
  client:
    container_name: client
    build:
      context: ./client
    working_dir: /client
    command: npm run dev -- --host
    volumes:
      - ./client:/client
      - /client/node_modules
    ports:
      - "5173:5173"
    restart: on-failure
    networks:
      - public_network
    depends_on:
      - api

  api:
    container_name: api
    build:
      context: ./api
    working_dir: /api
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - api/.env
    volumes:
      - ./api:/api
    ports:
      - "8000:8000"
    restart: on-failure
    networks:
      - public_network
      - private_network

networks:
  public_network:
  private_network:
